spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eBankifySecurity
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
      format-sql: true
  liquibase:
    change-log: classpath:db/master.yml
    enabled: true